; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
src_dir = ./
[env:black_f407vg]
platform = ststm32
board = black_f407vg
;framework = stm32cube
build_flags = 
    -mfloat-abi=hard
    -mfpu=fpv4-sp-d16
    -D USE_HAL_DRIVER
    -D STM32F407xx -DARM_MATH_CM4 -DARM_MATH_MATRIX_CHECK -DARM_MATH_ROUNDING
    -ICore/Inc
    -IDrivers/CMSIS/Device/ST/STM32F4xx/Include
    -IDrivers/CMSIS/Include
    -IDrivers/STM32F4xx_HAL_Driver/Inc
    -IDrivers/STM32F4xx_HAL_Driver/Inc/Legacy
    -IMiddlewares/Third_Party/FreeRTOS/Source/include
    -IMiddlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F
    -IMiddlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS
    -Wl,-u,_printf_float
build_src_filter = 
    +<Core/Src> 
    +<Drivers/STM32F4xx_HAL_Driver> 
    +<Drivers/CMSIS/Device> 
    +<Middlewares> 
    +<startup_stm32f407xx.s>
    -<Drivers/CMSIS/DSP/Source/TransformFunctions/arm_bitreversal2.c>
    -<Drivers/CMSIS/Core/Template>
    -<Drivers/CMSIS/Core_A>
    -<Drivers/CMSIS/DAP>
board_build.ldscript = stm32f407vgtx_flash.ld
upload_protocol = jlink
debug_tool = jlink
extra_scripts = update_link_flags.py
